#!/usr/bin/env bash
# Install Nginx on server & create a redirect

apt update
apt -y install nginx
echo "Hello World!" > /var/www/html/index.html
echo "server {
  	listen 80 default_server;
  	listen [::]:80 default_server;

  	root /var/www/html;

  	index index.html index.htm index.nginx-debian.html;

  	server_name _;

  	location /redirect_me {
          return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;
  	}

  	location / {
  	}
}" > /etc/nginx/sites-available/default
service nginx restart
