#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd

while IFS= read -r line; do
  IFS=':' read -ra fields <<< "$line"
  printf "The user %s is part of the %s gang, \
lives in %s and rides %s. \
%s's place is protected by the passcode %s, \
more info about the user here: %s\n" "${fields[0]}" "${fields[3]}" \
    "${fields[5]}" "${fields[6]}" "${fields[2]}" "${fields[1]}" \
    "${fields[4]}"
done < /etc/passwd
